BooksBlog/Areas/Administration/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooksBlog.Data;
using BooksBlog.Models;
using BooksBlog.Services.Contracts;
using BooksBlog.Areas.Administration.ViewModels;
using Microsoft.AspNet.Identity;
using BooksBlog.Controllers;

namespace BooksBlog.Areas.Administration.Controllers
{
    public class CategoryController : BaseController
    {
        private ICategoryService categoryService;
        private IUsersService usersService;

        public CategoryController(ICategoryService categoryService, IUsersService usersService)
        {
            this.categoryService = categoryService;
            this.usersService = usersService;
        }

        // GET: Administration/Category
        public ActionResult Index()
        {
            var categories = Mapper.Map<List<Categories>,
                List<CategoryViewModel>>(categoryService.GetAll().ToList());

            return View(categories);
        }

        // GET: Administration/Category/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Categories categories = db.Categories.Find(id);
        //    if (categories == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(categories);
        //}

        // GET: Administration/Category/Create
        public ActionResult Create()
        {
            CategoryViewModel categoryVM = new CategoryViewModel();
            return View(categoryVM);
        }

        // POST: Administration/Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                var dbCategory= Mapper.Map<Categories>(category);
                dbCategory.Author = usersService.Find(User.Identity.GetUserId());
                this.categoryService.Add(dbCategory);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Administration/Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Categories category = this.categoryService.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            CategoryViewModel categoryVM = Mapper.
                Map<CategoryViewModel>(category);
            //postVM.Users = new SelectList(this.usersService.GetAll(), "Id", "Email", post.Id);
            return View(categoryVM);

        }

        // POST: Administration/Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                var dbCategory = Mapper.Map<Categories>(category);
                this.categoryService.Update(dbCategory);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Administration/Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categories category = this.categoryService.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Administration/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this.categoryService.Delete(id);
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

BooksBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooksBlog.Data;
using BooksBlog.Models;
using BooksBlog.Services.Contracts;
using BooksBlog.ViewModels;
using Microsoft.AspNet.Identity;
using BooksBlog.Services;
using BooksBlog.Areas.Administration.ViewModels;

namespace BooksBlog.Controllers
{
    public class CommentsController : BaseController
    {
        private ICommentService commentService;
        private IPostService postsService;
        private IUsersService usersService;

        public CommentsController(ICommentService commentService, IPostService postService, IUsersService usersService)
        {
            //this.cache = cache;
            this.commentService = commentService;
            this.postsService = postService;
            this.usersService = usersService;
        }

        [HttpGet]
        public ActionResult _AddComment(int Id)
        {

            return PartialView();
        }
        [HttpPost]
        public ActionResult AddCommentAjax(CommentViewModel commentViewModel, int postId)
        {

            if (ModelState.IsValid)
            {
                var dbComment = Mapper.Map<Comments>(commentViewModel);
                dbComment.Author = usersService.Find(User.Identity.GetUserId());
                dbComment.Post = postsService.Find(postId);
                this.commentService.Add(dbComment);
            }

            //var posts = Mapper.Map<List<Post>,
            //    List<GuestPostViewModel>>(postsService.GetAll().ToList());
                                   
            var post = Mapper.Map<GuestPostViewModel>(postsService.Find(postId));
            return PartialView("_commentsList", post);
        }

        // GET: Comments
        //public ActionResult Index()
        //{
        //    return View(db.Comments.ToList());
        //}

        //// GET: Comments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comments comments = db.Comments.Find(id);
        //    if (comments == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comments);
        //}

        //// GET: Comments/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Comments/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Content,CreatedOn,IsDeleted")] Comments comments)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Comments.Add(comments);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(comments);
        //}

        //// GET: Comments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comments comments = db.Comments.Find(id);
        //    if (comments == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comments);
        //}

        //// POST: Comments/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Content,CreatedOn,IsDeleted")] Comments comments)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(comments).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(comments);
        //}

        //// GET: Comments/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Comments comments = db.Comments.Find(id);
        //    if (comments == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comments);
        //}

        //// POST: Comments/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Comments comments = db.Comments.Find(id);
        //    db.Comments.Remove(comments);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

BooksBlog/Views/Shared/_AddComment.cshtml
@using BooksBlog.ViewModels
@model CommentViewModel
<h2>Create your comment</h2>

@using (Ajax.BeginForm("AddCommentAjax", "Comments", new { postId = ViewData["Id"] }, new AjaxOptions
        { HttpMethod = "Post",
            UpdateTargetId = "commentsList",
            OnSuccess =  "HelperClear"
        
}))
{

    <div>
        @Html.HiddenFor(m => m.Id)
        @Html.LabelFor(m => m.Content)
        @Html.TextBoxFor(m => m.Content, new { id="idcontent", @class = "form-contol" })
    </div>

    <input type="submit" />

}

<script type="text/javascript">

    function HelperClear()
    {
        $("#idcontent").val("");
    }

</script>

BooksBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books are wings</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                @Html.ActionLink("Books are wings", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (Roles.IsUserInRole("AppAdmin"))

                        { @Html.ActionLink("Posts", "Index", "Post", new { area = "Administration" }, null) }
                    </li>

                     <li>
                         @if (Roles.IsUserInRole("AppAdmin"))
                                                     
                         { @Html.ActionLink("Categories","Index","Category", new { area = "Administration" }, null) }
                     </li>
                    <li>
                        @if (Roles.IsUserInRole("AppAdmin"))

                        { @Html.ActionLink("Users", "Index", "ApplicationUser", new { area = "Administration" }, null) }
                    </li>




                </ul>
                @Html.Partial("_LoginPartial")
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

 
    @RenderBody()

    <hr>
   
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; BOOKS 2016</p>
                </div>
            </div>
        </div>
    </footer>    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


@*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>*@

BooksBlog/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                @Html.ActionLink("A book is a version of the world. If you do not like it, ignore it or offer your own version in return.", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("home", "Index", "Home")
                    </li>
                    @*<li>
                            @Html.ActionLink("about", "About", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("contact", "Contact", "Home")
                        </li>*@
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Books 2016</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BooksBlog/Views/Shared/_categoryList.cshtml
@model IEnumerable<BooksBlog.Areas.Administration.ViewModels.CategoryViewModel>

@foreach (var item in Model)
{
<li>
            @Html.ActionLink(item.Name, "FilterByCategory", "Home", new { Id = item.Id }, null)
</li>}

BooksBlog/Views/Shared/_commentsList.cshtml
@using BooksBlog.ViewModels;
@model GuestPostViewModel


<table class="table">
    <thead>
        <tr>
            <th>Comments</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var comment in Model.Comments)
            {
            <tr><td>@comment.Content</td></tr>
            <tr><td>Commented by @comment.Author.UserName</td></tr>
        }

    </tbody>
</table>

BooksBlog/Views/Shared/_featuredPosts.cshtml
@model IEnumerable<BooksBlog.ViewModels.GuestPostViewModel>

@foreach (var item in Model)
{
    <li>
        @Html.ActionLink(item.Title, "Info", "Home", new { Id = item.Id }, null)
    </li>}